name: Github Action for node api

on: # WHAT'S TRIGGER GITHUB ACTION
   #pull_request:
    #branches: [ main ]
   push:
    branches: [main]

jobs: # list of jobs we want to run
  # this workflow contains a single job called "build"
  build: 
    # the type of runner that job will run on
    runs-on: self-hosted #because we are going to work on our virtual private server / ubuntu for linux/windows etc

    strategy:
      matrix:
      # [12.x, 14.x, 16.x] in this case jobs will be done three times - each one for every node version(we leave one) 
        node-version: [16.x] 
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # stepes represent a sequence of tasks that will be executed as part of the job
    steps:
   # - uses: actions/checkout@v2 # 
      name: Use Node.js ${{ matrix.node-version }} # set up node.js environment
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci # install all dependencies
      - run: npm build --if-present