# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Continuous Integration

on: # these are events that trigger sets of actions defined in jobs
  push: # events & branches on which this events happen
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: # name of the job -> it groups a set of actions that will be executed

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # path actions -> is where predefined actions are hosted on github with checkout version 2
    # uses - works somehow like an import from action.yml already defined on github actions
    - uses: actions/checkout@v2 
    # setup-node -> another already defined actions which prepares environment to be used with node
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: command description - npm ci
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
