name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deployment
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: "ec2-linux.pem"
          REMOTE_HOST: "ec2-54-93-74-176.eu-central-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/anotherFolder"