on:
    push:
        branches:
            - main
    pull_request:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: aws-actions/configure-aws-credentials@v1
                with: # first is key id, then is token
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   id: deploy
                uses: webfactory/create-aws-codedeploy-deployment@v0.2.2
        