name: Node CI

on: fork

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete" # optional - default
          SOURCE: "dist/" # optional 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # required
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # required
          TARGET: ${{ secrets.REMOTE_TARGET }} # optional
