name: testing api on pull requests
on: pull_request
jobs:
  tests:
    runs-on: self-hosted
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test